### ISSUE TITLE
CLI seems to expect args in a certain order

### ISSUE THREAD

**Issue by tomholford** [ashelkovnykov/offline-wallet-generator#10]
# Steps
1. Run the following command, but with the flags in different orders:
```sh
WALLET_ID=$(date +%s) WALLET_CURRENCY=BTC bin/owg-local.sh -o ~/.wallets/cold/$WALLET_CURRENCY/$WALLET_ID -p cold -c $WALLET_CURRENCY
```
For example:
```sh
WALLET_ID=$(date +%s) WALLET_CURRENCY=BTC bin/owg-local.sh -o ~/.wallets/cold/$WALLET_CURRENCY/$WALLET_ID -c $WALLET_CURRENCY -p cold
```

# Expected behavior

A user can call `owg` with the required flags (`-o`, `-p`, etc.) in different order permutations, and the wallet should be generated as expected.

# Actual behavior
output varies, perhaps depends on the order of flags?
```sh
SEVERE: Expected a command, got -c
```

```sh
SEVERE: Was passed main parameter '-o' but no main parameter was defined in your arg class
```

**Comment by ashelkovnykov** [comment]
The way JCommander works, it treats options after the command (e.g. `hot`/`cold`) as options for the command. Thus, from JCommander's perspective, a valid call to OWG looks like:
```
./bin/owg-local.sh [shared options] [command] [command options]
```
This expectation (as well as what options and commands exist) are documented by the JCommander auto-generated usage message, though I understand why such a firm requirement might be confusing/annoying to any experienced shell user.

There's no resolution to this (as far as I know) without switching to a different CLI manager, which I'd rather not do.

**Comment by ashelkovnykov** [comment]
Won't Do
